Repository all3dp/printing-engine-client, pull requests merged in 2018-12, with the labels that each got.

#908 Remove provider progress and add loading checkmark
  src/app/component/loading-checkmark/_loading-checkmark.scss
  src/app/component/loading-checkmark/index.js
  src/app/component/loading-checkmark/loading-checkmark.js
  src/app/component/loading-checkmark/loading-checkmark.story.js
  src/app/component/price/_price.scss
  src/app/component/price/price.js
  src/app/component/price/price.story.js
  src/app/container/material-partial.js
  src/app/container/upload-page.js
Labels: needs fixing

#912 Remove model viewer polling and fix critical model viewer bug
  src/app/action/index.ts
  src/app/action/modal.ts
  src/app/action/model-viewer.ts
  src/app/container/cart-page.js
  src/app/container/modal/model-viewer.js
  src/app/container/review-order-page.js
  src/app/container/upload-page.js
  src/app/reducer/index.ts
  src/app/reducer/model-viewer.ts
Labels: needs review

#920 Replace model thumbnail loading fallback image
  src/asset/image/model-thumbnail-fallback.png
Labels: enhancement
