Repository all3dp/printing-engine-client, pull requests merged in 2019-07, with the labels that each got.

#1202 Add page impression tracking
  src/app/index.js
  src/app/service/google-analytics.ts
Labels: needs review

#1203 Preload user from local storage
  config/default.ts
  src/app/container/modal/address-form.js
  src/app/reducer/core.ts
  src/app/service/local-storage.ts
Labels: needs review

#1204 Open model preview on preview image click
  src/app/component/cart-model-item/_cart-model-item.scss
  src/app/component/cart-model-item/cart-model-item.js
  src/app/component/cart-model-item/cart-model-item.story.js
  src/app/component/upload-model-item/_upload-model-item.scss
  src/app/component/upload-model-item/upload-model-item.js
  src/app/component/upload-model-item/upload-model-item.story.js
  src/app/container/cart-page.js
  src/app/container/edit-material-page.js
  src/app/container/material-page.js
  src/app/container/upload-page.js
Labels: needs review

#1205 Release: restore user from local storage, track page impressions, model item update
  config/default.ts
  src/app/component/cart-model-item/_cart-model-item.scss
  src/app/component/cart-model-item/cart-model-item.js
  src/app/component/cart-model-item/cart-model-item.story.js
  src/app/component/upload-model-item/_upload-model-item.scss
  src/app/component/upload-model-item/upload-model-item.js
  src/app/component/upload-model-item/upload-model-item.story.js
  src/app/container/cart-page.js
  src/app/container/edit-material-page.js
  src/app/container/material-page.js
  src/app/container/modal/address-form.js
  src/app/container/upload-page.js
  src/app/index.js
  src/app/reducer/core.ts
  src/app/service/google-analytics.ts
  src/app/service/local-storage.ts
Labels: work in progress

#1207 Fix missing local storage issue
  src/app/service/local-storage.ts
Labels: needs review

#1136 Refactor modals and add transition
  src/app/component/labeled-loading-indicator/_labeled-loading-indicator.scss
  src/app/component/labeled-loading-indicator/labeled-loading-indicator.js
  src/app/component/modal-portal/_modal-portal.scss
  src/app/component/modal-portal/index.js
  src/app/component/modal-portal/modal-portal.js
  src/app/component/modal-portal/modal-portal.story.js
  src/app/component/modal/_modal.scss
  src/app/component/modal/index.js
  src/app/component/modal/modal.js
  src/app/component/modal/modal.story.js
  src/app/component/overlay/index.js
  src/app/component/overlay/overlay.js
  src/app/component/overlay/overlay.story.js
  src/app/component/price/price.story.js
  src/app/container/modal/address-form.js
  src/app/container/modal/confirm-currency-change.js
  src/app/container/modal/confirm-location-change.js
  src/app/container/modal/error.js
  src/app/container/modal/fatal-error.js
  src/app/container/modal/finish-group.js
  src/app/container/modal/index.js
  src/app/container/modal/material.js
  src/app/container/modal/model-viewer.js
  src/app/container/modal/pick-location.js
  src/app/container/modal/pick-unit.js
  src/app/container/modal/share-configuration.js
  src/sass/_config.scss
  src/sass/util/_scrolling.scss
  test/cypress/integration/simple.spec.js
Labels: needs review

#1209 Fix flyout positioning issue
  src/app/component/cart-flyout/_cart-flyout.scss
  src/app/component/cart-flyout/cart-flyout.js
  src/app/component/cart-nav-link/cart-nav-link.js
  src/app/component/cart-nav-link/cart-nav-link.story.js
Labels: needs review

#1210 Release: Local storage issues, fix cart flyout positioning
  src/app/component/cart-flyout/_cart-flyout.scss
  src/app/component/cart-flyout/cart-flyout.js
  src/app/component/cart-nav-link/cart-nav-link.js
  src/app/component/cart-nav-link/cart-nav-link.story.js
  src/app/component/labeled-loading-indicator/_labeled-loading-indicator.scss
  src/app/component/labeled-loading-indicator/labeled-loading-indicator.js
  src/app/component/modal-portal/_modal-portal.scss
  src/app/component/modal-portal/index.js
  src/app/component/modal-portal/modal-portal.js
  src/app/component/modal-portal/modal-portal.story.js
  src/app/component/modal/_modal.scss
  src/app/component/modal/index.js
  src/app/component/modal/modal.js
  src/app/component/modal/modal.story.js
  src/app/component/overlay/index.js
  src/app/component/overlay/overlay.js
  src/app/component/overlay/overlay.story.js
  src/app/component/price/price.story.js
  src/app/container/modal/address-form.js
  src/app/container/modal/confirm-currency-change.js
  src/app/container/modal/confirm-location-change.js
  src/app/container/modal/error.js
  src/app/container/modal/fatal-error.js
  src/app/container/modal/finish-group.js
  src/app/container/modal/index.js
  src/app/container/modal/material.js
  src/app/container/modal/model-viewer.js
  src/app/container/modal/pick-location.js
  src/app/container/modal/pick-unit.js
  src/app/container/modal/share-configuration.js
  src/app/service/local-storage.ts
  src/sass/_config.scss
  src/sass/util/_scrolling.scss
  test/cypress/integration/simple.spec.js
Labels: needs review

#1214 Fix local storage issues
  src/app/service/local-storage.ts
Labels: needs review

#1220 Add ad blocker warning
  src/app/container/cart-page.js
  src/app/hook/use-has-adblocker.js
Labels: needs review

#1213 Update address form
  src/app/component/checkbox-field/_checkbox-field.scss
  src/app/component/checkbox-field/checkbox-field.js
  src/app/component/checkbox-field/checkbox-field.story.js
  src/app/component/country-select-field/_country-select-field.scss
  src/app/component/country-select-field/country-select-field.js
  src/app/component/country-select-field/country-select-field.story.js
  src/app/component/country-select-field/index.js
  src/app/component/input-field/_input-field.scss
  src/app/component/input-field/input-field.js
  src/app/component/input-field/input-field.story.js
  src/app/component/labeled-checkbox/_labeled-checkbox.scss
  src/app/component/labeled-checkbox/labeled-checkbox.js
  src/app/component/labeled-checkbox/labeled-checkbox.story.js
  src/app/component/select-field/_select-field.scss
  src/app/component/select-field/select-field.js
  src/app/component/select-field/select-field.story.js
  src/app/container/cart-page.js
  src/app/container/modal/address-form.js
  src/app/container/util/form.js
  src/app/lib/validator.spec.js
  src/app/lib/validator.ts
  src/sass/_config.scss
Labels: needs fixing

#1221 Save core state in local storage on unload
  config/default.ts
  src/app/index.js
  src/app/reducer/core.ts
  src/app/service/local-storage-session.ts
  src/app/service/location.ts
Labels: needs review

#1216 Implement new Stripe Checkout flow
  src/app/container/cart-page.js
  src/app/container/success-page.js
  src/app/external.d.ts
  src/app/index.html
  src/app/lib/printing-engine.spec.js
  src/app/lib/printing-engine.ts
  src/app/service/stripe.ts
Labels: needs review

#1224 Switch to development build for development branch
  .travis.yml
  package.json
Labels: needs review

#1223 Update card address text
  src/app/container/cart-page.js
Labels: needs review

#1226 Fix release issues
  src/app/component/button/_button.scss
  src/app/component/button/button.js
  src/app/component/button/button.story.js
  src/app/component/nav-link/nav-link.js
  src/app/container/cart-page.js
  src/app/container/footer-partial.js
  src/app/container/modal/address-form.js
  src/app/container/nav-bar-partial.js
  src/app/container/upload-page.js
  src/app/service/intercom.ts
Labels: needs review

#1228 Fix spacings in address form
  src/app/component/country-select-field/_country-select-field.scss
  src/app/container/modal/address-form.js
Labels: needs review

#1225 Release last sprint
  config/default.ts
  src/app/component/button/_button.scss
  src/app/component/button/button.js
  src/app/component/button/button.story.js
  src/app/component/checkbox-field/_checkbox-field.scss
  src/app/component/checkbox-field/checkbox-field.js
  src/app/component/checkbox-field/checkbox-field.story.js
  src/app/component/country-select-field/_country-select-field.scss
  src/app/component/country-select-field/country-select-field.js
  src/app/component/country-select-field/country-select-field.story.js
  src/app/component/country-select-field/index.js
  src/app/component/input-field/_input-field.scss
  src/app/component/input-field/input-field.js
  src/app/component/input-field/input-field.story.js
  src/app/component/labeled-checkbox/_labeled-checkbox.scss
  src/app/component/labeled-checkbox/labeled-checkbox.js
  src/app/component/labeled-checkbox/labeled-checkbox.story.js
  src/app/component/nav-link/nav-link.js
  src/app/component/select-field/_select-field.scss
  src/app/component/select-field/select-field.js
  src/app/component/select-field/select-field.story.js
  src/app/container/cart-page.js
  src/app/container/footer-partial.js
  src/app/container/modal/address-form.js
  src/app/container/nav-bar-partial.js
  src/app/container/success-page.js
  src/app/container/upload-page.js
  src/app/container/util/form.js
  src/app/external.d.ts
  src/app/hook/use-has-adblocker.js
  src/app/index.html
  src/app/index.js
  src/app/lib/printing-engine.spec.js
  src/app/lib/printing-engine.ts
  src/app/lib/validator.spec.js
  src/app/lib/validator.ts
  src/app/reducer/core.ts
  src/app/service/intercom.ts
  src/app/service/local-storage-session.ts
  src/app/service/local-storage.ts
  src/app/service/location.ts
  src/app/service/stripe.ts
  src/sass/_config.scss
Labels: needs review

#1230 Remove sentry release script
  .travis.yml
  bin/create-sentry-release.sh
  bin/get-sentry-release-version.sh
Labels: needs review

#1229 Fix stripe redirect bug
  src/app/service/stripe.ts
Labels: needs review

#1232 Add missing sentry release version
  bin/get-sentry-release-version.sh
Labels: needs review

#1231 Fix local storage access error
  src/app/service/local-storage.ts
Labels: needs review

#1233 Update contact texts on cart page
  src/app/container/cart-page.js
Labels: needs review

#1227 Add share cart button
  src/app/action/modal.ts
  src/app/component/headline/_headline.scss
  src/app/component/link/_link.scss
  src/app/component/link/link.js
  src/app/component/link/link.story.js
  src/app/component/page-header/_page-header.scss
  src/app/component/page-header/page-header.js
  src/app/component/page-header/page-header.story.js
  src/app/container/cart-page.js
  src/app/container/modal/index.js
  src/app/container/modal/share-cart.js
  src/app/reducer/core.ts
  src/app/type.ts
Labels: needs review
