Repository all3dp/printing-engine-client, pull requests merged in 2019-02, with the labels that each got.

#945 Refactor address page to formik and use a modal instead
  package-lock.json
  package.json
  src/app/action/modal.ts
  src/app/action/navigation.ts
  src/app/component/checkbox-field/checkbox-field.js
  src/app/component/form-row/_form-row.scss
  src/app/component/headline/_headline.scss
  src/app/component/headline/headline.js
  src/app/component/input-field/input-field.js
  src/app/component/labeled-checkbox/labeled-checkbox.js
  src/app/component/number-field/number-field.js
  src/app/component/overlay/_overlay.scss
  src/app/component/paypal-button/paypal-button.js
  src/app/component/radio-button-group/radio-button-group.js
  src/app/component/search-field/search-field.js
  src/app/component/select-field/select-field.js
  src/app/component/select-menu-item/select-menu-item.js
  src/app/container/address-page.js
  src/app/container/cart-page.js
  src/app/container/checkout-layout.js
  src/app/container/material-partial.js
  src/app/container/modal/address-form.js
  src/app/container/modal/index.js
  src/app/container/review-order-page.js
  src/app/container/util/form.js
  src/app/reducer/index.ts
  src/app/router.js
  src/app/service/scroll-to.ts
  src/app/type.ts
Labels: needs review

#955 Prevent errors from legacy address data
  src/app/container/modal/address-form.js
Labels: needs review

#958 Fix unit change issue
  src/app/container/modal/pick-unit.js
Labels: needs review

#960 Don't close address modal on click outside
  src/app/component/overlay/overlay.js
  src/app/component/overlay/overlay.story.js
  src/app/container/modal/address-form.js
Labels: needs review

#950 Refactor UploadModelItem and deprecate old one
  package-lock.json
  package.json
  src/app/component/checkbox-field/_checkbox-field.scss
  src/app/component/checkbox-field/checkbox-field.js
  src/app/component/checkbox-field/checkbox-field.story.js
  src/app/component/deprecated-upload-model-item-error/_deprecated-upload-model-item-error.scss
  src/app/component/deprecated-upload-model-item-error/deprecated-upload-model-item-error.js
  src/app/component/deprecated-upload-model-item-error/deprecated-upload-model-item-error.story.js
  src/app/component/deprecated-upload-model-item-error/index.js
  src/app/component/deprecated-upload-model-item-load/_deprecated-upload-model-item-load.scss
  src/app/component/deprecated-upload-model-item-load/deprecated-upload-model-item-load.js
  src/app/component/deprecated-upload-model-item-load/deprecated-upload-model-item-load.story.js
  src/app/component/deprecated-upload-model-item-load/index.js
  src/app/component/deprecated-upload-model-item/_deprecated-upload-model-item.scss
  src/app/component/deprecated-upload-model-item/deprecated-upload-model-item.js
  src/app/component/deprecated-upload-model-item/deprecated-upload-model-item.story.js
  src/app/component/deprecated-upload-model-item/index.js
  src/app/component/file-name/file-name.js
  src/app/component/file-name/file-name.story.js
  src/app/component/labeled-checkbox/_labeled-checkbox.scss
  src/app/component/labeled-checkbox/labeled-checkbox.js
  src/app/component/model-item/_model-item.scss
  src/app/component/model-list/_model-list.scss
  src/app/component/model-list/model-list.story.js
  src/app/component/upload-model-item-error/index.js
  src/app/component/upload-model-item-error/upload-model-item-error.js
  src/app/component/upload-model-item-error/upload-model-item-error.story.js
  src/app/component/upload-model-item-load/index.js
  src/app/component/upload-model-item/_upload-model-item.scss
  src/app/component/upload-model-item/upload-model-item.js
  src/app/component/upload-model-item/upload-model-item.story.js
  src/app/container/modal/confirm-currency-change.js
  src/app/container/upload-page.js
  src/app/lib/file.spec.js
  src/app/lib/file.ts
  src/asset/image/model-thumbnail-fallback.png
  src/sass/_config.scss
Labels: needs review

#961 Add location-info-partial
  src/app/action/modal.ts
  src/app/component/overlay/_overlay.scss
  src/app/container/location-info-partial.js
  src/app/container/modal/address-form.js
  src/app/container/modal/pick-location.js
  src/app/container/upload-page.js
  src/app/reducer/core.ts
Labels: needs review

#962 Add model item error and load
  src/app/component/upload-model-item-error/_upload-model-item-error.scss
  src/app/component/upload-model-item-error/index.js
  src/app/component/upload-model-item-error/upload-model-item-error.js
  src/app/component/upload-model-item-error/upload-model-item-error.story.js
  src/app/component/upload-model-item-load/_upload-model-item-load.scss
  src/app/component/upload-model-item-load/index.js
  src/app/component/upload-model-item-load/upload-model-item-load.js
  src/app/component/upload-model-item-load/upload-model-item-load.story.js
Labels: needs review

#963 Add upload layout component
  src/app/component/upload-layout/_upload-layout.scss
  src/app/component/upload-layout/index.js
  src/app/component/upload-layout/upload-layout.js
  src/app/component/upload-layout/upload-layout.story.js
Labels: needs review

#968 Increase the splash logo size
  src/app/index.html
Labels: needs review

#971 Replace Craftcloud logo with new logo
  src/asset/image/bootsplash.svg
  src/asset/image/logo.svg
Labels: enhancement, frontend

#973 Only allow valid values in the location field
  src/app/component/location-field/_location-field.scss
  src/app/component/location-field/location-field.js
Labels: needs review

#966 Use new upload layout on the upload page
  src/app/component/configuration-header/_configuration-header.scss
  src/app/component/location-field/_location-field.scss
  src/app/component/location-field/location-field.js
  src/app/component/upload-layout/_upload-layout.scss
  src/app/component/upload-layout/index.js
  src/app/component/upload-layout/upload-layout.js
  src/app/component/upload-layout/upload-layout.story.js
  src/app/component/upload-model-item-error/_upload-model-item-error.scss
  src/app/component/upload-model-item-error/index.js
  src/app/component/upload-model-item-error/upload-model-item-error.js
  src/app/component/upload-model-item-error/upload-model-item-error.story.js
  src/app/component/upload-model-item-load/_upload-model-item-load.scss
  src/app/component/upload-model-item-load/index.js
  src/app/component/upload-model-item-load/upload-model-item-load.js
  src/app/component/upload-model-item-load/upload-model-item-load.story.js
  src/app/container/app-layout.js
  src/app/container/cart-page.js
  src/app/container/edit-material-page.js
  src/app/container/material-page.js
  src/app/container/nav-bar-partial.js
  src/app/container/success-page.js
  src/app/container/upload-page.js
  src/app/index.html
  src/app/router.js
  src/asset/image/bootsplash.svg
  src/asset/image/logo.svg
Labels: Blocked

#975 Add material page
  config/default.ts
  package-lock.json
  src/app/action/navigation.ts
  src/app/component/button-bar/_button-bar.scss
  src/app/component/button/_button.scss
  src/app/component/configuration-header/_configuration-header.scss
  src/app/component/image-container/_image-container.scss
  src/app/component/material-slider/_material-slider.scss
  src/app/component/page-layout/page-layout.story.js
  src/app/component/tool-layout/_tool-layout.scss
  src/app/component/tool-layout/tool-layout.js
  src/app/component/tool-layout/tool-layout.story.js
  src/app/component/upload-layout/_upload-layout.scss
  src/app/component/upload-layout/upload-layout.js
  src/app/component/upload-layout/upload-layout.story.js
  src/app/container/app-layout.js
  src/app/container/cart-page.js
  src/app/container/edit-material-page.js
  src/app/container/material-page.js
  src/app/container/material-partial.js
  src/app/container/model-list-partial.js
  src/app/container/nav-bar-partial.js
  src/app/container/review-order-page.js
  src/app/container/success-page.js
  src/app/container/upload-page.js
  src/app/router.js
  src/app/service/scroll-to.ts
Labels: needs review

#970 Fix scrolling in address form
  src/app/component/overlay/overlay.js
  src/app/container/modal/address-form.js
Labels: needs review

#982 Prevent autocomplete on all text inputs
  src/app/component/input-field/input-field.js
  src/app/component/number-field/number-field.js
Labels: needs review

#987 Update master into develop branch
  src/app/component/input-field/input-field.js
  src/app/component/number-field/number-field.js
Labels: needs review

#995 Add robots.txt to dist build
  src/asset/robots.txt
  webpack.config.js
Labels: frontend, needs review

#1000 Change upload page button text
  src/app/container/upload-page.js
Labels: needs review

#999 Add robots.txt to dist build
  src/asset/robots.txt
  webpack.config.js
Labels: needs review

#1001 Remove onClick on ProviderBox
  src/app/component/provider-box/provider-box.js
  src/app/container/material-partial.js
Labels: needs review

#1002 Make Image clickable for select and deselect on UploadModelItem
  src/app/component/upload-model-item/_upload-model-item.scss
  src/app/component/upload-model-item/upload-model-item.js
  src/app/component/upload-model-item/upload-model-item.story.js
Labels: needs review

#965 Fix cypress tests
  package-lock.json
  package.json
  src/app/container/configuration-page.js
  src/app/container/review-order-page.js
  src/app/index.js
  test/cypress/integration/simple.spec.js
Labels: needs fixing

#1004 Fix reset action (with the exception of user handling)
  src/app/reducer/core.ts
Labels: needs review

#985 Integrate quantity change into edit material page and cart page
  src/app/component/number-field/_number-field.scss
  src/app/component/payment-section/payment-section.js
  src/app/container/cart-page.js
  src/app/container/edit-material-page.js
  src/app/container/review-order-page.js
  src/app/container/util/guard.js
  src/app/lib/formatter.spec.js
  src/app/lib/formatter.ts
  src/app/lib/model.spec.js
  src/app/lib/model.ts
  src/app/lib/selector.spec.js
  src/app/lib/selector.ts
  src/app/reducer/core.ts
  src/app/type.ts
Labels: needs review

#1003 Add refresh freature to model upload and add cypress test to travis
  .travis.yml
  config/cypress.ts
  config/index.ts
  package-lock.json
  package.json
  src/app/action/model.ts
  src/app/container/modal/pick-unit.js
  src/app/lib/printing-engine.spec.js
  src/app/lib/printing-engine.ts
  src/app/reducer/core.ts
  webpack.config.js
Labels: needs review

#981 Add new upload list
  .eslintrc
  src/app/component/container/_container.scss
  src/app/component/container/container.js
  src/app/component/container/container.story.js
  src/app/component/model-upload-list/_model-upload-list.scss
  src/app/component/model-upload-list/index.js
  src/app/component/model-upload-list/model-upload-list.js
  src/app/component/model-upload-list/model-upload-list.story.js
  src/app/component/upload-area/_upload-area.scss
  src/app/component/upload-area/upload-area.js
  src/app/component/upload-area/upload-area.story.js
  src/app/component/upload-layout/_upload-layout.scss
  src/app/component/upload-model-item/upload-model-item.js
  src/app/container/upload-page.js
  test/cypress/integration/simple.spec.js
Labels: needs review
