Repository all3dp/printing-engine-client, pull requests merged in 2019-03, with the labels that each got.

#1006 Update material page
  package-lock.json
  src/app/component/button/_button.scss
  src/app/component/button/button.js
  src/app/component/button/button.story.js
  src/app/component/color-card-list/_color-card-list.scss
  src/app/component/color-card-list/color-card-list.js
  src/app/component/color-card-list/color-card-list.story.js
  src/app/component/color-card-list/index.js
  src/app/component/color-card/_color-card.scss
  src/app/component/color-card/color-card.js
  src/app/component/color-card/color-card.story.js
  src/app/component/color-card/index.js
  src/app/component/color-square/color-square.js
  src/app/component/color-square/color-square.story.js
  src/app/component/color-square/index.js
  src/app/component/color-trait/_color-trait.scss
  src/app/component/color-trait/color-trait.js
  src/app/component/color-trait/color-trait.story.js
  src/app/component/color-trait/index.js
  src/app/component/material-card/_material-card.scss
  src/app/component/material-card/material-card.js
  src/app/component/material-card/material-card.story.js
  src/app/component/material-slider/material-slider.story.js
  src/app/component/material-step-headline/_material-step-headline.scss
  src/app/component/material-step-headline/index.js
  src/app/component/material-step-headline/material-step-headline.js
  src/app/component/material-step-headline/material-step-headline.story.js
  src/app/component/model-quantity-item/_model-quantity-item.scss
  src/app/component/price/_price.scss
  src/app/component/price/price.js
  src/app/component/price/price.story.js
  src/app/component/select-field/_select-field.scss
  src/app/component/select-field/select-field.js
  src/app/component/select-field/select-field.story.js
  src/app/component/select-menu-item/_select-menu-item.scss
  src/app/component/select-menu-item/select-menu-item.js
  src/app/component/select-menu-item/select-menu-item.story.js
  src/app/component/select-menu/select-menu.js
  src/app/component/select-menu/select-menu.story.js
  src/app/container/material-partial.js
  src/app/lib/offer.spec.js
  src/app/lib/offer.ts
  src/sass/_config.scss
  stories/util/data.js
  test/cypress/integration/simple.spec.js
Labels: needs review

#1008 Fix color trait border
  src/app/component/color-trait/_color-trait.scss
  src/app/component/color-trait/color-trait.js
Labels: needs review

#1010 Add production time to model item delivery indication
  src/app/component/model-item/model-item.js
  src/app/container/cart-page.js
  src/app/container/review-order-page.js
  src/app/lib/selector.spec.js
  src/app/lib/selector.ts
Labels: needs review

#1005 Integrate offer partial
  src/app/component/description-list/_description-list.scss
  src/app/component/description-list/description-list.js
  src/app/component/description-list/description-list.story.js
  src/app/component/material-step-headline/_material-step-headline.scss
  src/app/component/material-step-headline/material-step-headline.js
  src/app/component/material-step-headline/material-step-headline.story.js
  src/app/component/offer-footer/_offer-footer.scss
  src/app/component/offer-footer/index.js
  src/app/component/offer-footer/offer-footer.js
  src/app/component/offer-footer/offer-footer.story.js
  src/app/component/offer-item/_offer-item.scss
  src/app/component/offer-item/index.js
  src/app/component/offer-item/offer-item.js
  src/app/component/offer-item/offer-item.story.js
  src/app/component/offer-layout/_offer-layout.scss
  src/app/component/offer-layout/index.js
  src/app/component/offer-layout/offer-layout.js
  src/app/component/offer-layout/offer-layout.story.js
  src/app/component/provider-image/_provider-image.scss
  src/app/component/provider-image/provider-image.js
  src/app/component/provider-image/provider-image.story.js
  src/app/container/edit-material-page.js
  src/app/container/material-page.js
  src/app/container/material-partial.js
  src/app/container/offer-partial.js
  src/app/lib/offer.spec.js
  src/app/lib/offer.ts
  src/sass/_config.scss
  src/sass/main.scss
Labels: needs review

#1017 Integrate use-proof service
  src/app/index.html
Labels: needs review

#1016 Fix app reset and restore the user if possible
  src/app/action/core.ts
  src/app/container/review-order-page.js
  src/app/reducer/core.ts
  src/app/type.ts
Labels: needs fixing

#1018 Show price differences in material page
  src/app/component/offer-layout/_offer-layout.scss
  src/app/container/material-partial.js
  src/app/container/offer-partial.js
  src/app/lib/formatter.spec.js
  src/app/lib/formatter.ts
  src/app/lib/offer.spec.js
  src/app/lib/offer.ts
Labels: needs review

#1020 Fix reset material state after offer selection
  src/app/container/material-page.js
  src/app/container/material-partial.js
  src/app/container/offer-partial.js
Labels: needs review

#1021 Fix offer rendering when no materialConfigId is selected
  src/app/container/offer-partial.js
Labels: needs review

#1025 Update sentry cli module
  package-lock.json
  package.json
Labels: Showstopper, bug

#1027 Make company name required
  src/app/container/modal/address-form.js
Labels: needs review

#1026 Add order status page
  src/app/component/loading-container/_loading-container.scss
  src/app/component/loading-container/loading-container.js
  src/app/component/order-confirmation-item/_order-confirmation-item.scss
  src/app/component/order-confirmation-item/index.js
  src/app/component/order-confirmation-item/order-confirmation-item.js
  src/app/component/order-confirmation-item/order-confirmation-item.story.js
  src/app/component/order-confirmation-list/_order-confirmation-list.scss
  src/app/component/order-confirmation-list/index.js
  src/app/component/order-confirmation-list/order-confirmation-list.js
  src/app/component/order-confirmation-list/order-confirmation-list.story.js
  src/app/component/page-layout/_page-layout.scss
  src/app/component/page-layout/page-layout.js
  src/app/component/provider-teaser/_provider-teaser.scss
  src/app/container/app-layout.js
  src/app/container/app.js
  src/app/container/configuration-page.js
  src/app/container/edit-material-page.js
  src/app/container/order-status-page.js
  src/app/container/review-order-page.js
  src/app/container/success-page.js
  src/app/index.html
  src/app/index.js
  src/app/lib/printing-engine.spec.js
  src/app/lib/printing-engine.ts
  src/app/router.js
  src/app/service/bootsplash.ts
  src/asset/icon/order-placed.svg
  src/asset/icon/order-received.svg
  src/asset/icon/order-shipped.svg
  src/asset/icon/order-started.svg
  src/sass/_config.scss
  src/sass/util/_bg.scss
  stories/decorator/bg-minor.js
Labels: needs review
