Repository all3dp/printing-engine-client, pull requests merged in 2019-01, with the labels that each got.

#917 Fix ie11 bug for removing the spashscreen
  src/app/index.js
Labels: needs review

#915 Hide loading checkmark with 30 delay
  src/app/component/loading-checkmark/_loading-checkmark.scss
  src/app/component/loading-checkmark/loading-checkmark.story.js
  src/app/container/material-partial.js
Labels: question

#916 Add error modifier to select-field
  src/app/component/select-field/_select-field.scss
  src/app/component/select-field/select-field.story.js
Labels: needs fixing

#914 Change size of the loading checkmark
  src/app/component/price/_price.scss
  src/app/component/price/price.js
Labels: needs review

#943 Refactor footer to reflect new design
  package.json
  src/app/component/app/app.js
  src/app/component/footer/_footer.scss
  src/app/component/footer/footer.js
  src/app/component/footer/footer.story.js
  src/app/component/link/_link.scss
  src/app/component/link/link.js
  src/app/component/link/link.story.js
  src/app/container/app-layout.js
  src/app/container/checkout-layout.js
  src/app/container/upload-page.js
  src/app/index.html
  src/app/lib/class-names.spec.js
  src/app/lib/class-names.ts
  src/app/prop-types.js
  stories/decorator/invert.js
Labels: needs review

#944 Update NavBar according to the new design
  src/app/component/app/_app.scss
  src/app/component/app/app.story.js
  src/app/component/configuration-header/_configuration-header.scss
  src/app/component/configuration-header/configuration-header.js
  src/app/component/icon-link/_icon-link.scss
  src/app/component/icon-link/icon-link.js
  src/app/component/icon-link/icon-link.story.js
  src/app/component/nav-bar/_nav-bar.scss
  src/app/component/nav-bar/nav-bar.js
  src/app/component/nav-bar/nav-bar.story.js
  src/app/container/app-layout.js
  src/app/container/checkout-layout.js
  src/app/container/edit-material-page.js
  src/app/container/upload-page.js
  src/asset/image/logo.svg
Labels: needs fixing

#926 Update webpack-dev-server dependency
  package-lock.json
  package.json
Labels: needs review

#925 Remove sudo:false from travis config
  .travis.yml
Labels: needs review

#946 Add ToolLayout
  src/app/component/app/app.js
  src/app/component/app/app.story.js
  src/app/component/app/index.js
  src/app/component/container/_container.scss
  src/app/component/page-layout/_page-layout.scss
  src/app/component/page-layout/index.js
  src/app/component/page-layout/page-layout.js
  src/app/component/page-layout/page-layout.story.js
  src/app/component/tool-layout/_tool-layout.scss
  src/app/component/tool-layout/index.js
  src/app/component/tool-layout/tool-layout.js
  src/app/component/tool-layout/tool-layout.story.js
  src/app/container/app-layout.js
  src/app/container/checkout-layout.js
  src/app/container/edit-material-page.js
  src/app/container/material-partial.js
  src/sass/_config.scss
Labels: needs review

#949 Add filename component
  src/app/component/file-name/_file-name.scss
  src/app/component/file-name/file-name.js
  src/app/component/file-name/file-name.story.js
  src/app/component/file-name/index.js
  src/app/component/nav-bar/nav-bar.story.js
Labels: needs review

#948 Update button and number field components
  src/app/component/button/_button.scss
  src/app/component/button/button.js
  src/app/component/button/button.story.js
  src/app/component/headline/headline.js
  src/app/component/material-card/material-card.js
  src/app/component/model-item/model-item.story.js
  src/app/component/model-list/model-list.story.js
  src/app/component/nav-bar/nav-bar.story.js
  src/app/component/notification/notification.story.js
  src/app/component/number-field/_number-field.scss
  src/app/component/number-field/number-field.js
  src/app/component/number-field/number-field.story.js
  src/app/component/overlay/overlay.story.js
  src/app/component/page-layout/page-layout.story.js
  src/app/component/payment-section/payment-section.story.js
  src/app/component/provider-list/provider-list.js
  src/app/component/provider-list/provider-list.story.js
  src/app/component/tool-layout/tool-layout.story.js
  src/app/component/upload-model-item/upload-model-item.story.js
  src/app/container/app-layout.js
  src/app/container/cart-page.js
  src/app/container/checkout-layout.js
  src/app/container/material-partial.js
  src/app/container/modal/confirm-currency-change.js
  src/app/container/modal/confirm-location-change.js
  src/app/container/modal/pick-location.js
  src/app/container/modal/pick-unit.js
  src/app/container/model-list-partial.js
  src/app/container/review-order-page.js
  src/app/container/upload-page.js
Labels: needs review

#951 Fix number field
  src/app/component/number-field/_number-field.scss
  src/app/component/number-field/number-field.js
Labels: needs review

#952 Replace shapeways logo with new graphic
  src/asset/image/printing-service/shapeways.png
Labels: enhancement, frontend
